export const FETCH_ARTICLES_PENDING = 'FETCH_ARTICLES_PENDING';
export const FETCH_ARTICLES_FULFILLED = 'FETCH_ARTICLES_FULFILLED';
export const FETCH_ARTICLES_REJECTED = 'FETCH_ARTICLES_REJECTED';

export const LOAD_MORE_PENDING = 'LOAD_MORE_PENDING';
export const LOAD_MORE_FULFILLED = 'LOAD_MORE_FULFILLED';
export const LOAD_MORE_REJECTED = 'LOAD_MORE_REJECTED';

export const FETCH_POST_PENDING = 'FETCH_POST_PENDING';
export const FETCH_POST_FULFILLED = 'FETCH_POST_FULFILLED';
export const FETCH_POST_REJECTED = 'FETCH_POST_REJECTED';

export const FETCH_ARTICLES_LIKE_PENDING = 'FETCH_ARTICLES_LIKE_PENDING';
export const FETCH_ARTICLES_LIKE_FULFILLED = 'FETCH_ARTICLES_LIKE_FULFILLED';
export const FETCH_ARTICLES_LIKE_REJECTED = 'FETCH_ARTICLES_LIKE_REJECTED';