export const FETCH_ARTICLES_PENDING = 'FETCH_ARTICLES_PENDING';
export const FETCH_ARTICLES_FULFILLED = 'FETCH_ARTICLES_FULFILLED';
export const FETCH_ARTICLES_REJECTED = 'FETCH_ARTICLES_REJECTED';

export const FETCH_POST_PENDING = 'FETCH_POST_PENDING';
export const FETCH_POST_FULFILLED = 'FETCH_POST_FULFILLED';
export const FETCH_POST_REJECTED = 'FETCH_POST_REJECTED';

export const FETCH_ARTICLES_LIKE_PENDING = 'FETCH_ARTICLES_LIKE_PENDING';
export const FETCH_ARTICLES_LIKE_FULFILLED = 'FETCH_ARTICLES_LIKE_FULFILLED';
export const FETCH_ARTICLES_LIKE_REJECTED = 'FETCH_ARTICLES_LIKE_REJECTED';