export const FETCH_COMMENTS_PENDING = 'FETCH_COMMENTS_PENDING';
export const FETCH_COMMENTS_FULFILLED = 'FETCH_COMMENTS_FULFILLED';
export const FETCH_COMMENTS_REJECTED = 'FETCH_COMMENTS_REJECTED';

export const FETCH_ALL_COMMENTS_PENDING = 'FETCH_ALL_COMMENTS_PENDING';
export const FETCH_ALL_COMMENTS_FULFILLED = 'FETCH_ALL_COMMENTS_FULFILLED';
export const FETCH_ALL_COMMENTS_REJECTED = 'FETCH_ALL_COMMENTS_REJECTED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const CHANGE_HEIGHT = 'CHANGE_HEIGHT';
export const CHANGE_VISIBLE = 'CHANGE_VISIBLE';
export const ADD_REPLY = 'ADD_REPLY';
export const DELETE_REPLY = 'DELETE_REPLY';